/* =========================================================
   GUIDEON Schema v9.7 (Final)
   PostgreSQL 15+ / PostGIS / pgvector / pg_trgm

   OUTER = zone_id NULL (no boundary polygon)

   CHANGE (v9.7 patch):
   - tb_zone.level is NOT provided by client.
   - level is derived from zone_type (INNER=1, SUB=2) as a GENERATED column.
   ========================================================= */

BEGIN;

-- 0) Extensions
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- 1) updated_at auto trigger function
CREATE OR REPLACE FUNCTION guideon_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 2) ENUM types
DO $$ BEGIN
  CREATE TYPE zone_source_enum AS ENUM ('AUTO', 'MANUAL');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE info_type_enum AS ENUM ('NOTICE', 'HOURS', 'MENU_SIMPLE', 'PRICE');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE doc_status_enum AS ENUM ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE actor_type_enum AS ENUM ('ADMIN', 'SYSTEM', 'DEVICE');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE action_type_enum AS ENUM ('CREATE', 'UPDATE', 'DELETE');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- (추가) 관리자 역할: 플랫폼/관광지 운영자
DO $$ BEGIN
  CREATE TYPE admin_role_enum AS ENUM ('PLATFORM_ADMIN', 'SITE_ADMIN');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- (추가) 초대 상태: PENDING(미사용) / USED(사용됨) / EXPIRED(만료) / REVOKED(회수)
DO $$ BEGIN
  CREATE TYPE admin_invite_status_enum AS ENUM ('PENDING', 'USED', 'EXPIRED', 'REVOKED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- =========================================================
-- 3) Tables
-- =========================================================

-- 3.1 tb_site
CREATE TABLE IF NOT EXISTS tb_site (
  site_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR(100) NOT NULL,
  is_active   BOOLEAN NOT NULL DEFAULT TRUE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE tb_site IS '관광지/테넌트 Root. 모든 데이터는 site 단위로 격리.';
COMMENT ON COLUMN tb_site.site_id IS '모든 하위 테이블의 Root Key';
COMMENT ON COLUMN tb_site.name IS '관광지명';
COMMENT ON COLUMN tb_site.is_active IS 'Kill switch. FALSE면 해당 관광지 기능 차단';
COMMENT ON COLUMN tb_site.created_at IS '생성 시각';
COMMENT ON COLUMN tb_site.updated_at IS '수정 시각(트리거 자동 갱신)';

CREATE TRIGGER trg_site_updated_at
BEFORE UPDATE ON tb_site
FOR EACH ROW EXECUTE FUNCTION guideon_set_updated_at();

-- =========================================================
-- 3.1.1 tb_admin
-- =========================================================
CREATE TABLE IF NOT EXISTS tb_admin (
  admin_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email          VARCHAR(255) NOT NULL,
  password_hash  VARCHAR(255) NOT NULL, -- bcrypt/argon2 등 해시 결과 저장(평문 금지)
  role           admin_role_enum NOT NULL DEFAULT 'SITE_ADMIN',
  is_active      BOOLEAN NOT NULL DEFAULT TRUE,
  last_login_at  TIMESTAMPTZ NULL,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uk_admin_email UNIQUE (email)
);

COMMENT ON TABLE tb_admin IS '관리자 계정(PLATFORM_ADMIN / SITE_ADMIN).';
COMMENT ON COLUMN tb_admin.admin_id IS '관리자 PK';
COMMENT ON COLUMN tb_admin.email IS '로그인 이메일(유니크). 애플리케이션에서 소문자 정규화 권장';
COMMENT ON COLUMN tb_admin.password_hash IS '비밀번호 해시';
COMMENT ON COLUMN tb_admin.role IS 'PLATFORM_ADMIN(전체) / SITE_ADMIN(특정 관광지)';
COMMENT ON COLUMN tb_admin.is_active IS '비활성 시 로그인/기능 차단';
COMMENT ON COLUMN tb_admin.last_login_at IS '마지막 로그인 시각';
COMMENT ON COLUMN tb_admin.created_at IS '생성 시각';
COMMENT ON COLUMN tb_admin.updated_at IS '수정 시각(트리거 자동 갱신)';

CREATE INDEX IF NOT EXISTS idx_admin_role_active ON tb_admin (role, is_active);

CREATE TRIGGER trg_admin_updated_at
BEFORE UPDATE ON tb_admin
FOR EACH ROW EXECUTE FUNCTION guideon_set_updated_at();

-- =========================================================
-- 3.1.2 tb_admin_site : SITE_ADMIN 접근 스코프
-- =========================================================
CREATE TABLE IF NOT EXISTS tb_admin_site (
  admin_id   BIGINT NOT NULL REFERENCES tb_admin(admin_id) ON DELETE CASCADE,
  site_id    BIGINT NOT NULL REFERENCES tb_site(site_id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (admin_id, site_id)
);

COMMENT ON TABLE tb_admin_site IS 'SITE_ADMIN이 접근 가능한 관광지(site) 스코프 매핑.';
COMMENT ON COLUMN tb_admin_site.admin_id IS '관리자 PK';
COMMENT ON COLUMN tb_admin_site.site_id IS '관광지 PK';
COMMENT ON COLUMN tb_admin_site.created_at IS '매핑 생성 시각';

CREATE INDEX IF NOT EXISTS idx_admin_site_site_id ON tb_admin_site (site_id);

-- =========================================================
-- 3.1.3 tb_admin_invite : 초대 기반 계정 발급
-- =========================================================
CREATE TABLE IF NOT EXISTS tb_admin_invite (
  invite_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_id             BIGINT NOT NULL REFERENCES tb_site(site_id) ON DELETE CASCADE,

  email               VARCHAR(255) NOT NULL,
  role                admin_role_enum NOT NULL DEFAULT 'SITE_ADMIN',

  token_hash          CHAR(64) NOT NULL, -- SHA-256 HEX (평문 저장 금지)
  status              admin_invite_status_enum NOT NULL DEFAULT 'PENDING',
  expires_at          TIMESTAMPTZ NOT NULL,
  used_at             TIMESTAMPTZ NULL,

  created_by_admin_id BIGINT NULL REFERENCES tb_admin(admin_id) ON DELETE SET NULL,

  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT uk_invite_token_hash UNIQUE (token_hash)
);

COMMENT ON TABLE tb_admin_invite IS '관광지 운영자 초대(회원가입 대체). token은 hash만 저장.';
COMMENT ON COLUMN tb_admin_invite.invite_id IS '초대 PK';
COMMENT ON COLUMN tb_admin_invite.site_id IS '초대 대상 관광지';
COMMENT ON COLUMN tb_admin_invite.email IS '초대 이메일';
COMMENT ON COLUMN tb_admin_invite.role IS '기본 SITE_ADMIN';
COMMENT ON COLUMN tb_admin_invite.token_hash IS '초대 토큰 SHA-256(HEX)';
COMMENT ON COLUMN tb_admin_invite.status IS 'PENDING/USED/EXPIRED/REVOKED';
COMMENT ON COLUMN tb_admin_invite.expires_at IS '만료 시각';
COMMENT ON COLUMN tb_admin_invite.used_at IS '사용 시각(수락 완료)';
COMMENT ON COLUMN tb_admin_invite.created_by_admin_id IS '초대 발급한 관리자(보통 PLATFORM_ADMIN)';
COMMENT ON COLUMN tb_admin_invite.created_at IS '생성 시각';
COMMENT ON COLUMN tb_admin_invite.updated_at IS '수정 시각(트리거 자동 갱신)';

-- 같은 site+email로 "활성(PENDING)" 초대는 1개만 허용
CREATE UNIQUE INDEX IF NOT EXISTS uk_invite_site_email_pending
ON tb_admin_invite (site_id, email)
WHERE status = 'PENDING';

CREATE INDEX IF NOT EXISTS idx_invite_site_status ON tb_admin_invite (site_id, status);
CREATE INDEX IF NOT EXISTS idx_invite_expires_at ON tb_admin_invite (expires_at);

CREATE TRIGGER trg_admin_invite_updated_at
BEFORE UPDATE ON tb_admin_invite
FOR EACH ROW EXECUTE FUNCTION guideon_set_updated_at();

-- =========================================================
-- 3.2 tb_zone (INNER/SUB only. OUTER is NULL)
--   - level: GENERATED ALWAYS AS (zone_type 기반)
-- =========================================================
CREATE TABLE IF NOT EXISTS tb_zone (
  zone_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_id        BIGINT NOT NULL REFERENCES tb_site(site_id) ON DELETE CASCADE,
  name           VARCHAR(50) NOT NULL,
  code           VARCHAR(50) NOT NULL,
  zone_type      VARCHAR(10) NOT NULL, -- 'INNER' or 'SUB'

  -- IMPORTANT: 클라이언트/서버가 입력하지 않음. zone_type으로 자동 결정(INNER=1, SUB=2)
  level          SMALLINT GENERATED ALWAYS AS (
    CASE zone_type
      WHEN 'INNER' THEN 1
      WHEN 'SUB'   THEN 2
    END
  ) STORED,

  parent_zone_id BIGINT NULL REFERENCES tb_zone(zone_id) ON DELETE SET NULL,
  area_geometry  geometry(Polygon, 4326) NOT NULL,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT uk_zone_code UNIQUE (site_id, code),
  -- composite FK를 위해 (zone_id, site_id) 유니크 제공
  CONSTRAINT uk_zone_id_site UNIQUE (zone_id, site_id),
  CONSTRAINT ck_zone_type CHECK (zone_type IN ('INNER', 'SUB'))
);

COMMENT ON TABLE tb_zone IS '구역(Zone). INNER/SUB만 저장. OUTER는 zone_id NULL로 표현.';
COMMENT ON COLUMN tb_zone.zone_id IS '구역 ID';
COMMENT ON COLUMN tb_zone.site_id IS '소속 관광지';
COMMENT ON COLUMN tb_zone.name IS '관리자 UI 표시용';
COMMENT ON COLUMN tb_zone.code IS '시스템 식별 코드(site 내 유니크). 예: INNER, SUB_A';
COMMENT ON COLUMN tb_zone.zone_type IS 'INNER 또는 SUB. OUTER는 저장하지 않음';
COMMENT ON COLUMN tb_zone.level IS '파생 컬럼(Generated). zone_type으로 자동 결정: INNER=1, SUB=2 (클라이언트 입력 금지)';
COMMENT ON COLUMN tb_zone.parent_zone_id IS 'SUB의 부모 INNER';
COMMENT ON COLUMN tb_zone.area_geometry IS '구역 폴리곤(geometry, SRID 4326). ST_Contains 기준';
COMMENT ON COLUMN tb_zone.created_at IS '생성 시각';
COMMENT ON COLUMN tb_zone.updated_at IS '수정 시각(트리거 자동 갱신)';

CREATE INDEX IF NOT EXISTS idx_zone_geom_gist ON tb_zone USING GIST (area_geometry);
CREATE INDEX IF NOT EXISTS idx_zone_site_type ON tb_zone (site_id, zone_type, level);
CREATE INDEX IF NOT EXISTS idx_zone_parent ON tb_zone (parent_zone_id);

CREATE TRIGGER trg_zone_updated_at
BEFORE UPDATE ON tb_zone
FOR EACH ROW EXECUTE FUNCTION guideon_set_updated_at();

-- =========================================================
-- 3.3 tb_place
-- =========================================================
CREATE TABLE IF NOT EXISTS tb_place (
  place_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_id      BIGINT NOT NULL REFERENCES tb_site(site_id) ON DELETE CASCADE,

  zone_id      BIGINT NULL,
  zone_source  zone_source_enum NOT NULL DEFAULT 'AUTO',

  name         VARCHAR(100) NOT NULL,
  name_json    JSONB NULL,
  category     VARCHAR(50) NOT NULL,

  -- 정확한 거리(미터) 계산을 위해 geography 사용
  location     geography(Point, 4326) NOT NULL,

  description  TEXT NULL,
  image_url    VARCHAR(500) NULL,
  is_active    BOOLEAN NOT NULL DEFAULT TRUE,

  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- 하위 테이블 무결성용(복합 FK 타겟)
  CONSTRAINT uk_place_id_site UNIQUE (place_id, site_id),

  -- zone도 site가 일치해야 함(OUTER면 zone_id NULL)
  CONSTRAINT fk_place_zone_site
    FOREIGN KEY (zone_id, site_id)
    REFERENCES tb_zone(zone_id, site_id)
    ON DELETE SET NULL
);

COMMENT ON TABLE tb_place IS '장소(POI). 거리검색 기준점. OUTER는 zone_id NULL.';
COMMENT ON COLUMN tb_place.place_id IS '장소 ID';
COMMENT ON COLUMN tb_place.site_id IS '소속 관광지';
COMMENT ON COLUMN tb_place.zone_id IS '캐싱된 구역 ID. OUTER면 NULL';
COMMENT ON COLUMN tb_place.zone_source IS '구역 할당 출처(AUTO=자동계산, MANUAL=관리자 보정)';
COMMENT ON COLUMN tb_place.name IS '기본 장소명(한국어)';
COMMENT ON COLUMN tb_place.name_json IS '다국어 장소명 JSONB(선택)';
COMMENT ON COLUMN tb_place.category IS '카테고리(TOILET/TICKET/RESTAURANT 등)';
COMMENT ON COLUMN tb_place.location IS '장소 좌표(geography). ST_Distance로 미터 계산';
COMMENT ON COLUMN tb_place.description IS 'UI 표시용 설명';
COMMENT ON COLUMN tb_place.image_url IS '썸네일 이미지 URL';
COMMENT ON COLUMN tb_place.is_active IS 'FALSE면 공사/폐쇄 등으로 검색/안내 제외';
COMMENT ON COLUMN tb_place.created_at IS '생성 시각';
COMMENT ON COLUMN tb_place.updated_at IS '수정 시각(트리거 자동 갱신)';

CREATE INDEX IF NOT EXISTS idx_place_loc_gist ON tb_place USING GIST (location);
CREATE INDEX IF NOT EXISTS idx_place_filter ON tb_place (site_id, category, is_active);
CREATE INDEX IF NOT EXISTS idx_place_site_active ON tb_place (site_id, is_active);

CREATE TRIGGER trg_place_updated_at
BEFORE UPDATE ON tb_place
FOR EACH ROW EXECUTE FUNCTION guideon_set_updated_at();

-- =========================================================
-- 3.4 tb_device
-- =========================================================
CREATE TABLE IF NOT EXISTS tb_device (
  device_id      VARCHAR(50) PRIMARY KEY,
  auth_token_hash CHAR(64) NOT NULL, -- SHA-256 hex

  site_id         BIGINT NOT NULL REFERENCES tb_site(site_id) ON DELETE CASCADE,

  zone_id         BIGINT NULL,
  zone_source     zone_source_enum NOT NULL DEFAULT 'AUTO',

  location_name   VARCHAR(100) NOT NULL,
  location        geography(Point, 4326) NOT NULL,

  is_active       BOOLEAN NOT NULL DEFAULT TRUE,
  last_ping       TIMESTAMPTZ NULL,
  last_auth_at    TIMESTAMPTZ NULL,

  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT fk_device_zone_site
    FOREIGN KEY (zone_id, site_id)
    REFERENCES tb_zone(zone_id, site_id)
    ON DELETE SET NULL
);

COMMENT ON TABLE tb_device IS '키오스크 기기. 토큰은 해시만 저장. OUTER면 zone_id NULL.';
COMMENT ON COLUMN tb_device.device_id IS 'Unity config.json의 기기 ID';
COMMENT ON COLUMN tb_device.auth_token_hash IS '기기 인증 토큰 SHA-256(HEX) 해시';
COMMENT ON COLUMN tb_device.site_id IS '소속 관광지';
COMMENT ON COLUMN tb_device.zone_id IS '캐싱된 구역 ID. OUTER면 NULL';
COMMENT ON COLUMN tb_device.zone_source IS '구역 할당 출처(AUTO/MANUAL)';
COMMENT ON COLUMN tb_device.location_name IS '설치 위치명(UI 표시)';
COMMENT ON COLUMN tb_device.location IS '기기 좌표(geography)';
COMMENT ON COLUMN tb_device.is_active IS 'FALSE면 접속 차단';
COMMENT ON COLUMN tb_device.last_ping IS '헬스 체크(마지막 핑)';
COMMENT ON COLUMN tb_device.last_auth_at IS '마지막 인증 성공 시간';
COMMENT ON COLUMN tb_device.created_at IS '생성 시각';
COMMENT ON COLUMN tb_device.updated_at IS '수정 시각(트리거 자동 갱신)';

CREATE INDEX IF NOT EXISTS idx_device_loc_gist ON tb_device USING GIST (location);
CREATE INDEX IF NOT EXISTS idx_device_site_active ON tb_device (site_id, is_active);

CREATE TRIGGER trg_device_updated_at
BEFORE UPDATE ON tb_device
FOR EACH ROW EXECUTE FUNCTION guideon_set_updated_at();

-- =========================================================
-- 3.5 tb_mascot (site 1:1)
-- =========================================================
CREATE TABLE IF NOT EXISTS tb_mascot (
  mascot_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_id        BIGINT NOT NULL UNIQUE REFERENCES tb_site(site_id) ON DELETE CASCADE,

  name           VARCHAR(50) NOT NULL,
  model_id       VARCHAR(80) NOT NULL,
  default_anim   VARCHAR(50) NOT NULL DEFAULT 'IDLE_A',

  greeting_msg   VARCHAR(200) NOT NULL,
  system_prompt  TEXT NOT NULL,

  tts_voice_id   VARCHAR(50) NOT NULL,
  tts_voice_json JSONB NULL,

  is_active      BOOLEAN NOT NULL DEFAULT TRUE,

  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE tb_mascot IS '관광지별 마스코트 설정(외형/페르소나/보이스/인사말). site 1:1.';

CREATE TRIGGER trg_mascot_updated_at
BEFORE UPDATE ON tb_mascot
FOR EACH ROW EXECUTE FUNCTION guideon_set_updated_at();

-- =========================================================
-- 3.6 tb_document (meta)
-- =========================================================
CREATE TABLE IF NOT EXISTS tb_document (
  doc_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_id         BIGINT NOT NULL REFERENCES tb_site(site_id) ON DELETE CASCADE,

  original_name   VARCHAR(255) NOT NULL,
  storage_url     VARCHAR(500) NOT NULL,
  file_hash       CHAR(64) NOT NULL,
  file_size       BIGINT NULL,

  chunk_size      INT NOT NULL DEFAULT 500,
  chunk_overlap   INT NOT NULL DEFAULT 50,
  embedding_model VARCHAR(100) NOT NULL DEFAULT 'text-embedding-3-small',

  status          doc_status_enum NOT NULL DEFAULT 'PENDING',
  failed_reason   TEXT NULL,
  processed_at    TIMESTAMPTZ NULL,

  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT uk_doc_hash UNIQUE (site_id, file_hash),
  CONSTRAINT uk_doc_id_site UNIQUE (doc_id, site_id) -- tb_doc_chunk composite FK용
);

CREATE INDEX IF NOT EXISTS idx_doc_site_status ON tb_document (site_id, status);

CREATE TRIGGER trg_document_updated_at
BEFORE UPDATE ON tb_document
FOR EACH ROW EXECUTE FUNCTION guideon_set_updated_at();

-- =========================================================
-- 3.7 tb_doc_chunk (search engine)
-- =========================================================
CREATE TABLE IF NOT EXISTS tb_doc_chunk (
  chunk_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  site_id      BIGINT NOT NULL,
  doc_id       BIGINT NOT NULL,

  chunk_index  INT NOT NULL,
  content      TEXT NOT NULL,
  metadata     JSONB NULL,

  embedding    vector(1536) NULL,

  content_tsv  TSVECTOR GENERATED ALWAYS AS (
    to_tsvector('simple', coalesce(content, ''))
  ) STORED,

  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT fk_chunk_doc_site
    FOREIGN KEY (doc_id, site_id)
    REFERENCES tb_document(doc_id, site_id)
    ON DELETE CASCADE,

  CONSTRAINT uk_chunk_order UNIQUE (doc_id, chunk_index)
);

CREATE INDEX IF NOT EXISTS idx_chunk_embedding_hnsw
ON tb_doc_chunk USING hnsw (embedding vector_cosine_ops)
WHERE embedding IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_chunk_tsv_gin
ON tb_doc_chunk USING GIN (content_tsv);

CREATE INDEX IF NOT EXISTS idx_chunk_content_trgm
ON tb_doc_chunk USING GIN (content gin_trgm_ops);

-- =========================================================
-- 3.9 tb_daily_info
-- =========================================================
CREATE TABLE IF NOT EXISTS tb_daily_info (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  site_id     BIGINT NOT NULL,
  place_id    BIGINT NOT NULL,

  target_date DATE NOT NULL,
  info_type   VARCHAR(50) NOT NULL,
  content     TEXT NOT NULL,

  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT fk_daily_place_site
    FOREIGN KEY (place_id, site_id)
    REFERENCES tb_place(place_id, site_id)
    ON DELETE CASCADE,

  CONSTRAINT uk_daily UNIQUE (place_id, target_date, info_type)
);

CREATE INDEX IF NOT EXISTS idx_daily_site_date ON tb_daily_info (site_id, target_date);

CREATE TRIGGER trg_daily_updated_at
BEFORE UPDATE ON tb_daily_info
FOR EACH ROW EXECUTE FUNCTION guideon_set_updated_at();

-- =========================================================
-- 3.10 tb_audit_log
-- =========================================================
CREATE TABLE IF NOT EXISTS tb_audit_log (
  log_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_id      BIGINT NOT NULL REFERENCES tb_site(site_id) ON DELETE CASCADE,

  actor_type   actor_type_enum NOT NULL,
  actor_id     VARCHAR(50) NOT NULL,

  target_table VARCHAR(50) NOT NULL,
  target_pk    VARCHAR(64) NOT NULL,

  action_type  action_type_enum NOT NULL,
  changes_json JSONB NULL,

  ip_address   VARCHAR(45) NULL,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE tb_audit_log IS '감사 로그. actor_id는 ADMIN이면 admin:{admin_id} 권장.';
CREATE INDEX IF NOT EXISTS idx_audit_search ON tb_audit_log (site_id, target_table, created_at);

-- =========================================================
-- 4) Constraints (tb_zone consistency)
--   - level은 generated이므로 "parent 조건"만 강제하면 충분
-- =========================================================
ALTER TABLE tb_zone
ADD CONSTRAINT ck_zone_type_parent_consistency
CHECK (
  (zone_type = 'INNER' AND parent_zone_id IS NULL)
  OR
  (zone_type = 'SUB'   AND parent_zone_id IS NOT NULL)
);

COMMIT;
