from app.core.DB.connect_db import get_conn

SQL = """
-- schema.sql에서 정의된 테이블들이 준비되어 있는지 확인
-- tb_document, tb_doc_chunk는 schema.sql에서 생성됨

-- 혹시 schema.sql 실행 안 됐으면 여기서 명시적으로 생성 (선택사항)
-- 현재는 schema.sql 먼저 실행하고, 이 스크립트는 검증용

CREATE EXTENSION IF NOT EXISTS vector;

-- ENUM 타입 생성 (schema.sql과 동일)
DO $$ BEGIN
  CREATE TYPE doc_status_enum AS ENUM ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- tb_document 생성 여부 확인
CREATE TABLE IF NOT EXISTS tb_document (
  doc_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_id         BIGINT NOT NULL,

  original_name   VARCHAR(255) NOT NULL,
  storage_url     VARCHAR(500) NOT NULL,
  file_hash       CHAR(64) NOT NULL,
  file_size       BIGINT NULL,

  chunk_size      INT NOT NULL DEFAULT 500,
  chunk_overlap   INT NOT NULL DEFAULT 50,
  embedding_model VARCHAR(100) NOT NULL DEFAULT 'text-embedding-3-small',

  status          doc_status_enum NOT NULL DEFAULT 'PENDING',
  failed_reason   TEXT NULL,
  processed_at    TIMESTAMPTZ NULL,

  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- tb_doc_chunk 생성 여부 확인
CREATE TABLE IF NOT EXISTS tb_doc_chunk (
  chunk_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  site_id      BIGINT NOT NULL,
  doc_id       BIGINT NOT NULL,

  chunk_index  INT NOT NULL,
  content      TEXT NOT NULL,
  metadata     JSONB NULL,

  embedding    vector(1536) NULL,

  content_tsv  TSVECTOR GENERATED ALWAYS AS (
    to_tsvector('simple', coalesce(content, ''))
  ) STORED,

  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 벡터 검색 인덱스 (HNSW: 빠른 벡터 유사도 검색)
CREATE INDEX IF NOT EXISTS idx_chunk_embedding_hnsw
ON tb_doc_chunk USING hnsw (embedding vector_cosine_ops)
WHERE embedding IS NOT NULL;

-- 텍스트 검색 인덱스 (TSVector: 전문 검색)
CREATE INDEX IF NOT EXISTS idx_chunk_tsv_gin
ON tb_doc_chunk USING GIN (content_tsv);

-- 청크 조회 인덱스
CREATE INDEX IF NOT EXISTS idx_chunk_doc_site
ON tb_doc_chunk (doc_id, site_id);
"""

with get_conn() as conn:
    with conn.cursor() as cur:
        cur.execute(SQL)
    conn.commit()

print("✅ tb_document & tb_doc_chunk tables ready")
print("📌 주의: 먼저 schema.sql을 실행해야 정상 작동함!")
