"""
tb_doc_chunk_v2 테이블 생성 스크립트 (구조화 RAG 실험용)

기존 tb_doc_chunk는 그대로 유지하고, 새로운 v2 테이블만 추가 생성.
tb_document는 공유 (문서 메타데이터는 동일).

실행: python -m app.core.DB.create_table_v2
"""
from app.core.DB.connect_db import get_conn

SQL = """
CREATE EXTENSION IF NOT EXISTS vector;

-- =========================================================
-- tb_doc_chunk_v2 (구조화 RAG + Hybrid Search)
-- =========================================================
CREATE TABLE IF NOT EXISTS tb_doc_chunk_v2 (
  chunk_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  site_id       BIGINT NOT NULL,
  doc_id        BIGINT NOT NULL,

  chunk_index   INT NOT NULL,
  section_title TEXT,                 -- 마크다운 헤더에서 추출한 섹션 제목
  content       TEXT NOT NULL,        -- 원문 단락 (LLM 답변 생성용)
  summary       TEXT NOT NULL,        -- GPT가 생성한 검색용 요약
  keywords      TEXT[],               -- GPT가 추출한 키워드 배열

  embedding     vector(1536) NULL,    -- 요약 텍스트의 임베딩

  -- Hybrid Search용 tsvector (가중치: 요약/제목=A, 원문=B)
  search_tsv    TSVECTOR GENERATED ALWAYS AS (
    setweight(to_tsvector('simple', coalesce(summary, '')), 'A') ||
    setweight(to_tsvector('simple', coalesce(content, '')), 'B') ||
    setweight(to_tsvector('simple', coalesce(section_title, '')), 'A')
  ) STORED,

  metadata      JSONB NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT fk_chunk_v2_doc_site
    FOREIGN KEY (doc_id, site_id)
    REFERENCES tb_document(doc_id, site_id)
    ON DELETE CASCADE
);

-- HNSW 인덱스 (벡터 유사도 검색)
CREATE INDEX IF NOT EXISTS idx_chunk_v2_embedding_hnsw
ON tb_doc_chunk_v2 USING hnsw (embedding vector_cosine_ops)
WHERE embedding IS NOT NULL;

-- GIN 인덱스 (풀텍스트 검색)
CREATE INDEX IF NOT EXISTS idx_chunk_v2_tsv_gin
ON tb_doc_chunk_v2 USING GIN (search_tsv);

-- 중복 삽입 방지용 유니크 인덱스
CREATE UNIQUE INDEX IF NOT EXISTS uq_chunk_v2_site_doc_chunk
ON tb_doc_chunk_v2 (site_id, doc_id, chunk_index);

-- 조회용 인덱스
CREATE INDEX IF NOT EXISTS idx_chunk_v2_doc_site
ON tb_doc_chunk_v2 (doc_id, site_id);
"""

if __name__ == "__main__":
    with get_conn() as conn:
        with conn.cursor() as cur:
            cur.execute(SQL)
        conn.commit()
    print("[OK] tb_doc_chunk_v2 table created")
